### PR TITLE
extend cards with 0 and 0.5

### PR DESCRIPTION
**Pull request by pamapa**
I am working @siemens and we have regularly have m+f trainees. We are using this planning-poker from our scrum session. However we are missing 0 and 0.5 cards,

- extended with 0 and 0.5 card, which have been found and adapted from https://www.m-f.ch/blog/planning-poker-anleitung
- i made the 0 not 0 but 'zero' because all the JavaScript does check for !card (!null, !undefined or !0)

Would be cool when you can merge and deploy that sometime to herokuapp.com...

### CODE REVIEW

**Comment by justmejulian** [comment]
Thanks! Looks good!

**Comment by pamapa** [comment]
thanks for merging, would be nice if you could put that live to heroku sometime...

**Comment by justmejulian** [comment]
deployed 💪🏼

**Comment by pamapa** [comment]
cool thanks

**Comment by justmejulian** [comment]
Danke dir 😊

**Pull request merged**
